import express from 'express';
import authRoutes from './auth.js';
import expenseRoutes from './expenseRoute.js';
import goalRoutes from './goalRoutes.js';
import balanceRoutes from './balance.js';
import analysisRoutes from "./analysisRoutes.js";
import refundRoutes from "./refundRoutes.js";
import aiRoutes from "./aiRoutes.js";
import receiptRoutes from './receipt.js';
import alertRoutes from './alertRoute.js';
import recommendationRoutes from './recommendationRoutes.js';
const router=express.Router();

router.use('/auth', authRoutes); 
router.use('/goals', goalRoutes);
router.use('/balance', balanceRoutes);
router.use('/expenses', expenseRoutes);
router.use("/analysis", analysisRoutes);
router.use("/refunds", refundRoutes);
router.use("/api", aiRoutes);
router.use('/receipt-scan', receiptRoutes);
router.use('/alerts', alertRoutes);
router.use('/recommendations', recommendationRoutes);
export default router;